stages:
  - test

dbt-test:
  stage: test
  image: python:3.11
  script:
    - pip install dbt-snowflake
    - mkdir -p /root/.dbt
    - echo "gold_coast_labour_market:" > /root/.dbt/profiles.yml
    - echo "  outputs:" >> /root/.dbt/profiles.yml
    - echo "    dev:" >> /root/.dbt/profiles.yml
    - echo "      type: snowflake" >> /root/.dbt/profiles.yml
    - echo "      account: $SNOWFLAKE_ACCOUNT" >> /root/.dbt/profiles.yml
    - echo "      user: NORATECH" >> /root/.dbt/profiles.yml
    - echo "      password: $SNOWFLAKE_PASSWORD" >> /root/.dbt/profiles.yml
    - echo "      role: ACCOUNTADMIN" >> /root/.dbt/profiles.yml
    - echo "      database: GOLD_COAST_LABOUR_MARKET" >> /root/.dbt/profiles.yml
    - echo "      warehouse: COMPUTE_WH" >> /root/.dbt/profiles.yml
    - echo "      schema: RAW" >> /root/.dbt/profiles.yml
    - echo "      threads: 1" >> /root/.dbt/profiles.yml
    - echo "  target: dev" >> /root/.dbt/profiles.yml
    - echo "Account is $SNOWFLAKE_ACCOUNT"
    - cd dbt/gold_coast_labour_market
    - dbt test
