AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function for Gold Coast Labour Market Pipeline retrieving new data from s3 and sending to snowflake'

Parameters:
  BucketName:
    Type: String
    Description: 'Name of the S3 bucket where the Lambda function code is stored'

Resources:
  LambdaNewDataHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda-new-data-handler
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref BucketName
        S3Key: lambda-function.zip

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

Outputs:
  LambdaFunctionName:
    Description: 'Name of the Lambda function'
    Value: !Ref LambdaNewDataHandler
